# Generated by Django 5.0.6 on 2026-07-02 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('avg_engagement_score', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=20)),
                ('focus_time_seconds', models.IntegerField(default=0)),
                ('distraction_count', models.IntegerField(default=0)),
                ('total_frames_analyzed', models.IntegerField(default=0)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('avg_age', models.FloatField(blank=True, null=True)),
                ('dominant_gender', models.CharField(blank=True, max_length=10)),
                ('liveness_pass_rate', models.FloatField(default=100.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('attentive', models.BooleanField(default=True)),
                ('yaw', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracker.session')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='tracker_emo_session_e3aabf_idx')],
            },
        ),
    ]
